//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFinancialCrm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinancalCrmDbEntities2 : DbContext
    {
        public FinancalCrmDbEntities2()
            : base("name=FinancalCrmDbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankProcesses> BankProcesses { get; set; }
        public virtual DbSet<Banks> Banks { get; set; }
        public virtual DbSet<Bilss> Bilss { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Spendings> Spendings { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usres> Usres { get; set; }
    }
}
